### PR TITLE
Add Optimistic Updates section and details for refetch option in useQuery mutate()

### PR DESCRIPTION
**Pull request by shaunchurch**
Add a simple sentence explaining the option to disable refetch when calling mutate. https://github.com/blitz-js/blitz/pull/715

Added in all locations it was relevant, but if it's too much detail for the useQuery/useInfiniteQuery pages I can remove those and leave it only on the Mutation Usage details. Thoughts?

### CODE REVIEW

**Comment by flybayer** [comment]
@shaunchurch what you have looks good! Could you also add a section to https://blitzjs.com/docs/mutation-usage specifically for **Optimistic Updates**?

**Comment by shaunchurch** [comment]
@flybayer Ok, first draft in. I'm using the line highlighting from #101 , so this now depends on that being merged first.

**Comment by flybayer** [comment]
Beautiful!!

**Comment by flybayer** [comment]
@shaunchurch can you either update this PR or create a new one so that it's a pr into the `main` branch. `master` has been deleted.

**Pull request closed without merging**
