### PR TITLE
updated prisma migrate usage in docs

### PR DESCRIPTION
**Pull request by amdolan**
with prisma@2.19, migrate is no longer a preview feature, so we don't need that flag

NOTE: I suppose this shouldn't be merged to main until some time after the latest release and deploy.  There is the potential for confusion..  Here is the related pr: https://github.com/blitz-js/blitz/pull/2138

### CODE REVIEW

**Comment by JuanM04** [comment]
Perfect, thank you!
I'll put this in the Icebox meanwhile

**Comment by flybayer** [comment]
@JuanM04 what I do for feature changes like this is change the branch target to the `canary` branch. 

Then once I merge the blitz PR, I merge this too

**Comment by flybayer** [comment]
@JuanM04 does our bot properly handle this contribution use case?

**Comment by JuanM04** [comment]
Nope, only if it targets the default branch. Do you want me to change it?

**Comment by JuanM04** [comment]
@blitzjs-bot add contributor amdolan doc

**Pull request merged**
