### PR TITLE
Update deploy docs on how to have multiple providers in Prisma

### PR DESCRIPTION
**Pull request by victorferreira**

### CODE REVIEW

**Comment by theZieger** [comment]
I'm not a maintainer but I would prefer a normal code block over a diff for this documentation. Copy and paste is easier with normal code blocks. When using a diff you have to get rid of the + signs manually. But that's just my opinion. :slightly_smiling_face: 
Anyways, good to see this beeing added to the documentation. :+1:

**Comment by victorferreira** [comment]
I actually agree with you, but decided to keep the pattern already in use in the docs. One of the advantages of the diff is point to the exact spot of the modification by keeping the context. Also, the amount of characters do be removed here is very minimal.

If there's a standard I should follow here please let me know and I'll change it. 😃

**Comment by theZieger** [comment]
Totally fine. I guess one of the long term contributers could clarify this more easily.

**Comment by flybayer** [comment]
Thanks for the effort @victorferreira, however I don't think we should add this to the docs. Firstly, for any production application it is **highly** recommended to use the same db in dev as in prod. Otherwise you will eventually run into weird bugs.

Also, my understanding from the Prisma team is that this feature is going to be removed.

As for the diff highlighting, you can use [line highlighting](https://github.com/blitz-js/blitzjs.com#code-syntax-highlights) instead of the diff to highlight specific lines.

**Comment by victorferreira** [comment]
I'll close this PR, then.

Just out o curiosity, did the Prisma team document this anywhere?

**Comment by flybayer** [comment]
I wasn't able to find anything with a quick search

**Pull request closed without merging**
