### PR TITLE
Enable highlighting specific lines within code blocks

### PR DESCRIPTION
**Pull request by shaunchurch**
Closes: #98 

Upgraded to @theme-ui/prism 4.0-rc.1 for support for commented code highlighting like so:

```
const example = "not highlighted";
// highlight-start
const highlighted = true;
// highlight-end
const alsoHighlighted = true // highlight-line
```

Adds a custom CSS class to visually distinguish the highlighted lines.

### CODE REVIEW

**Comment by shaunchurch** [comment]
The CSS has a few magic numbers. I'm not sure if there's a better way to do this with theme-ui?

There's an issue on narrow screens where the highlighted div doesn't extend beyond the initial width of the <pre> that is scrollable. I don't know if there's way to force it full width within the <pre> tag.

Another option is to enable wrapping inside the <pre> tags with this:

```
pre.prism-code {
  white-space: pre-wrap;
  word-break: break-word;
}
```

**Comment by shaunchurch** [comment]
image

**Comment by flybayer** [comment]
@shaunchurch nice!!! Magic numbers are fine for now. We can revisit it once the full design is done.

One last thing, can you add a section to the readme of this repo on how to add line highlighting?

**Comment by shaunchurch** [comment]
Now with line numbers. "The try catch block on lines 8-12 in the example..."

They're in a :before pseudo element and done entirely in CSS so aren't included when selecting or copy and pasting examples.

image

**Comment by flybayer** [comment]
Awesome!! The line numbers are great!

But is there a way to disable line numbers for `sh` and `bash` type?

image

**Comment by shaunchurch** [comment]
@flybayer ah good spot. Yes, they each have a language class as well, so I've disabled sh, bash and the class that seems to apply to unspecified language back tick blocks.

**Comment by flybayer** [comment]
Yay!! Thank you!!!

**Pull request merged**
