### PR TITLE
Rembrandt/custom scrollbar comp306

### LINKED ISSUE #306: V2 - Add a custom scrollbar for the homepage
The architecture diagram and the "Everything You Need For Production Apps" features list need a custom scrollbar so it's visible and obviously scrollable.

### PR DESCRIPTION
**Pull request by rembrandtreyes**
Closes #306 

Creating a custom scrollbar component to be used within the new site

Current functionality
* Horizontal scroll

TODO:
* Implement in the architecture section.
* Make sure color schemes match what is in the Figma document.

Note: I will probably leave the vertical scrolling for another PR. I will create an issue that way someone else can pick it up if they would llike.

### CODE REVIEW

**Comment by flybayer** [comment]
Hey @rembrandtreyes FYI I'm wanting to get the site fully finished asap this week for the beta launch, likely next week. Are you able to finish this?

**Comment by rembrandtreyes** [comment]
> Hey @rembrandtreyes FYI I'm wanting to get the site fully finished asap this week for the beta launch, likely next week. Are you able to finish this?

Hey @flybayer, I should have this done by tomorrow or Wednesday

**Comment by rembrandtreyes** [comment]
Screen Shot 2021-02-09 at 7 54 31 AM
Screen Shot 2021-02-09 at 7 54 24 AM
Screen Shot 2021-02-09 at 7 54 12 AM
Screen Shot 2021-02-09 at 7 54 02 AM

**Comment by flybayer** [comment]
@rembrandtreyes sweet, thank you!

**Pull request merged**
