### PR TITLE
V2-Remove Tailwind Content #255

### PR DESCRIPTION
**Pull request by cwray-tech**
## Removed the majority of the TW content from the new site.
For Issue #255 
- I left some components that I thought may end up being useful, namely the search, and version switcher, etc.
- I may have accidentally removed a necessary util or component. Love it if you could check this @flybayer 

## For the version switcher component: 
- I updated the util to pull in the Blitz version and updated the module naming to reference Blitz.

## In the Index page and layouts 
- I removed the content & updated meta info.
- I removed the object contents that created nav links in the sidebar layout as well as in the footer. **This needs to be added once that we have the docs added/more pages on the site.**

## Changes still needed
- In the public directory are the page meta images still using TW branding. These images need to be edited.
- In some components that I left, there were some svg's that I believe are TW logos. specifically in the Logo component, so may want to check that out.

### CODE REVIEW

**Comment by cwray-tech** [comment]
Btw not sure why the other commits from the last pull are in here. I did merge the upstream into my main branch before creating this branch.

**Comment by flybayer** [comment]
@cwray-tech probably something to do with your fork. For future PRs you can clone this repo directly. Don't need to use the fork since you have write access.

**Comment by flybayer** [comment]
Alright thanks for your work on this! I probably should have thought through my instructions a bit more.

- For a first pass, let's keep all the components, or at least most of them. There's quite a few which we can use like CodeWindow, etc.
- Secondly, leave some of the tailwind pages in place including some that export overrides from the mdx files. We need these as examples of how to use stuff. So maybe leave like two whole sections of docs.
- Leave the navigation and menu stuff in place for those pages.
- We don't need any of the version switcher stuff

**Comment by cwray-tech** [comment]
@flybayer sounds good. I will do my best to get those back in, maybe by tomorrow.
 Thank you!

**Comment by cwray-tech** [comment]
I'm closing this pr as to @flybayer and I's private convo about my time availability.

**Pull request closed without merging**
