### PR TITLE
Create layout for alpha homepage

### PR DESCRIPTION
**Pull request by mgm1313**
ToDo:
- [x] Style form input for newsletter subscription
- [x] Check responsiveness
- [x] Replace video placeholder with actual component (https://github.com/blitz-js/blitzjs.com/pull/42)

### CODE REVIEW

**Comment by robdrosenberg** [comment]
@mgm1313 We've decided to use Theme UI! Do you need any help finishing this PR? We'd like the site to go live before Friday (5/15)

**Comment by mgm1313** [comment]
@robdrosenberg Cool! Will be working on the PR again Wednesday/Thursday, so I keep you posted.

**Comment by ivandevp** [comment]
Is there anything here that I can help with?

**Comment by mgm1313** [comment]
Just pushed some new changes. 

I'd love some help with connecting the newsletter form to Mailchimp. I believe @flybayer owns the Mailchimp account, so I guess we should set it up to use a environment variable which Brandon then can set-up at Vercel. Maybe this is something you'd like to work on @ivandevp ?

Furthermore I put some content here and there, but would love for somebody to check/improve it. English isn't my native language, nor do I know everything about what Blitz has to offer, so I guess other people are far better and telling that story. 

@robdrosenberg I saw theme-ui is not merged into master yet so I haven't started using it yet. Meaning the overall theme is still mostly the default theme, which is not that exciting.

**Comment by ivandevp** [comment]
Sure @mgm1313! I will work on it, then.

**Comment by robdrosenberg** [comment]
@mgm1313 and @ivandevp Sorry I should have messaged you earlier, just been slammed the last few work days and needed some time away from the screen over the weekend.
I think we need to pause development on docusaurus v2. It's been very disruptive to our progress than we originally thought it would be even though we knew it was in alpha. I'm doing a little more research to see if we can pull the automatic theme out of it but I'm guessing it won't work. If we aren't able to theme it I think we might look into using a different docs solution or building something out custom. We really appreciate all your help with everything on the site so far, I'm trying to explore all options before we make the decision of discontinuing docusaurus v2.

**Pull request merged**
