### PR TITLE
Fix some broken links

### PR DESCRIPTION
**Pull request by exclipy**

### CODE REVIEW

**Comment by exclipy** [comment]
I scanned the site with deadlinkchecker.com and the only two remaining are the "you can see here" links at https://blitzjs.com/docs/api-routes

They look like they should link to https://nextjs.org/docs/api-routes/api-middlewares and https://nextjs.org/docs/api-routes/response-helpers respectively. Should I link there or were those pages supposed to be copy/pasted in to blitzjs.com?

**Comment by flybayer** [comment]
@exclipy awesome, thank you for this!!

And yes, those links on the api routes page should link to the proper page on blitzjs.com

**Comment by exclipy** [comment]
My question was that I couldn't find the proper page on blitzjs.com,so should I make them or should I link to nextjs.org?

**Comment by flybayer** [comment]
@exclipy ah yeah!

I just realized they are actually on the same page.

"Response Helpers" and "Default Middlewares"

**Comment by exclipy** [comment]
Ah of course, how did I miss that

**Comment by flybayer** [comment]
Perfect, thank you! :)

**Pull request merged**
