### PR TITLE
Initial pass at branding updates

### PR DESCRIPTION
**Pull request by jasonblalock**
- Colors, fonts, favicons, dark/light mode
- Found some issues that I noted in #25

### CODE REVIEW

**Comment by merelinguist** [comment]
Screenshot 2020-04-26 at 23 39 56

Can this be white all the time? The button too.

**Comment by jasonblalock** [comment]
> Screenshot 2020-04-26 at 23 39 56
> 
> Can this be white all the time? The button too.

I agree that I don't like how it looks (it's also not WCAG 2.0 compliant). But I was trying to hold off on doing one off customizations until we have a final design from our designer and make some decisions on things mentioned in #25 (the hero styling is using the built in Docusaurus design system that is using the updated color pallete). Especially since the docs aren't released.

**Comment by flybayer** [comment]
Looking fairly good for now.

But you can change all occurrences of "Blitz JS" to "Blitz.js"

**Comment by robdrosenberg** [comment]
@jasonblalock We've decided on Theme UI for styling! Let me know if you want to to continue finishing up this PR with Theme UI. We're trying to get the site live before Friday (5/15).
#55

**Pull request merged**
