### PR TITLE
Languages and Translations entry

### PR DESCRIPTION
**Pull request by JuanM04**
I added a very simple languages page. It's only meant to track the progress of each translation (for now)

Also, I added a entry in the docs with a bit of information for everyone who wants to translate Blitz. It's meant to be used in this situations:

> — Hey, how can I help translating Blitz?
> — https://blitzjs.com/docs/translations

### CODE REVIEW

**Comment by flybayer** [comment]
Sweet, thanks!!!

Maybe add "The React documentation is available in the following languages:" under the "Language" header like react has, which helps explain the page I think.

Also you have an min-height issue:

image

**Comment by flybayer** [comment]
You're a genius by the way. I love the automation here! :D

**Comment by JuanM04** [comment]
> Also you have an min-height issue

Yes, and the footer is behaving weirdly. I'm working on it

**Comment by JuanM04** [comment]
@flybayer Does the min-height error persists?

**Pull request merged**
